CREATE TABLE ENTIDADE_TESTE (
	ID INTEGER IDENTITY, 
	NOME VARCHAR(120)
);

INSERT INTO ENTIDADE_TESTE (NOME) VALUES ('Entidade Zero');
INSERT INTO ENTIDADE_TESTE (NOME) VALUES ('Entidade Um');
INSERT INTO ENTIDADE_TESTE (NOME) VALUES ('Entidade Dois');
INSERT INTO ENTIDADE_TESTE (NOME) VALUES ('Entidade Três');
INSERT INTO ENTIDADE_TESTE (NOME) VALUES ('Entidade Quatro');
INSERT INTO ENTIDADE_TESTE (NOME) VALUES ('Entidade Cinco');