--CRIA A TABELA ALUNOS
CREATE TABLE ALUNOS(
id_aluno LONG NOT NULL PRIMARY KEY,
matricula VARCHAR(15) NOT NULL,
nome VARCHAR(100) NOT NULL,
nota1 DECIMAL(4,2) NOT NULL,
nota2 DECIMAL (4,2) NOT NULL
);

